<?php
return [
    [
        'menu_name' => '报价管理',
        'menu_key' => 'phone_shop_price',
        'menu_short_name' => '报价',
        'parent_key' => 'setting_manage',
        'menu_type' => '0',
        'icon' => 'iconfont iconshangpinguanli',
        'api_url' => 'phone_shop_price/recycle_category_tree',
        'router_path' => 'recycle_category/recycle_category',
        'view_path' => 'recycle_category/recycle_category',
        'methods' => 'get',
        'sort' => '90',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '二手机分类列表',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_list',
                'menu_short_name' => '二手机分类列表',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category',
                'router_path' => 'recycle_category/recycle_category',
                'view_path' => 'recycle_category/recycle_category',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '二手机分类添加',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_add',
                'menu_short_name' => '二手机分类添加',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '二手机分类编辑',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_edit',
                'menu_short_name' => '二手机分类编辑',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '二手机分类删除',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_delete',
                'menu_short_name' => '二手机分类删除',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];