<?php
return [
    [
        'menu_name' => '手机回收系统',
        'menu_key' => 'phone_shop_price',
        'menu_short_name' => '回收',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconmobile',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '110',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '二手机分类列表',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_list',
                'menu_short_name' => '二手机分类列表',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category',
                'router_path' => 'recycle_category/recycle_category',
                'view_path' => 'recycle_category/recycle_category',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            // banner 
            [
                'menu_name' => '轮播管理',
                'menu_key' => 'recycle_banner',
                'menu_short_name' => '轮播',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_banner',
                'router_path' => 'recycle_banner',
                'view_path' => 'recycle_category/banner',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '分类列表等级获取',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category',
                'menu_short_name' => '分类列表等级获取',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '回收订单',
                'menu_key' => 'recycle_order',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'iconfont iconorder',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'recycle_order_list',
                        'menu_short_name' => '订单列表',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'phone_shop_price/recycle_order',
                        'router_path' => 'recycle_order/list',
                        'view_path' => 'recycle_order/list',
                        'methods' => 'get',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '删除订单',
                                'menu_key' => 'recycle_order_delete',
                                'menu_short_name' => '删除订单',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'phone_shop_price/recycle_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '编辑订单',
                                'menu_key' => 'recycle_order_edit',
                                'menu_short_name' => '编辑订单',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'phone_shop_price/recycle_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加订单',
                                'menu_key' => 'recycle_order_add',
                                'menu_short_name' => '添加订单',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'phone_shop_price/recycle_order',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'menu_name' => '二手机分类添加',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_add',
                'menu_short_name' => '二手机分类添加',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '二手机分类编辑',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_edit',
                'menu_short_name' => '二手机分类编辑',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '二手机分类删除',
                'menu_key' => 'phone_shop_price_phone_shop_recycle_category_recycle_category_recycle_category_delete',
                'menu_short_name' => '二手机分类删除',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'phone_shop_price/recycle_category/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];