<?php
return [
    [
        'menu_name' => '会员充值',
        'menu_key' => 'recharge',
        'menu_short_name' => '会员充值',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element Help',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '充值设置',
                'menu_key' => 'recharge_package_config',
                'menu_short_name' => '充值设置',
                'menu_type' => '1',
                'icon' => 'iconfont iconchongzhidingdan',
                'api_url' => '',
                'router_path' => 'recharge/package/config',
                'view_path' => 'package/config',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '充值套餐',
                'menu_key' => 'recharge_package_list',
                'menu_short_name' => '充值套餐',
                'menu_type' => '1',
                'icon' => 'iconfont iconchongzhidingdan',
                'api_url' => 'recharge/package',
                'router_path' => 'recharge/package/list',
                'view_path' => 'package/list',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '修改状态（开启、关闭）',
                        'menu_key' => 'recharge_package_close',
                        'menu_short_name' => '套餐关闭',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'recharge/package/status/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '套餐删除',
                        'menu_key' => 'recharge_package_delete',
                        'menu_short_name' => '套餐删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'recharge/package/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '订单列表',
                'menu_key' => 'recharge_order_list',
                'menu_short_name' => '订单列表',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'recharge/order',
                'router_path' => 'recharge/order/list',
                'view_path' => 'order/list',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '订单详情',
                'menu_key' => 'recharge_order_detail',
                'menu_short_name' => '订单详情',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'recharge/order/<order_id>',
                'router_path' => 'recharge/order/detail',
                'view_path' => 'order/detail',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '编辑套餐',
                'menu_key' => 'recharge_package_edit',
                'menu_short_name' => '编辑套餐',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'recharge_package/<id>',
                'router_path' => 'recharge/package/edit',
                'view_path' => 'package/edit',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '添加套餐',
                'menu_key' => 'recharge_package_add',
                'menu_short_name' => '添加套餐',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'recharge_package',
                'router_path' => 'recharge/package/add',
                'view_path' => 'package/edit',
                'methods' => 'post',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];