<?php
return [
    [
        'menu_name' => '群发助手',
        'menu_key' => 'qf_notice',
        'menu_short_name' => '群发助手',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '基础设置',
                'menu_key' => 'qf_notice_email',
                'menu_short_name' => '设置',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
                'api_url' => '',
                'router_path' => 'qf_notice/config',
                'view_path' => 'config/index',
                'methods' => 'post',
                'sort' => '120',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '应用管理',
                'menu_key' => 'qf_notice_qfnotice_category_category_category',
                'menu_short_name' => '应用',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-yingyongzhongxinV6xx',
                'api_url' => '',
                'router_path' => 'category',
                'view_path' => '',
                'methods' => '',
                'sort' => '102',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '应用列表',
                        'menu_key' => 'qf_notice_qfnotice_addon_addon_addon_list',
                        'menu_short_name' => '应用',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-lianjieV6xx1',
                        'api_url' => 'qf_notice/addon',
                        'router_path' => 'qf_addon/addon',
                        'view_path' => 'addon/addon',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '分类列表',
                        'menu_key' => 'qf_notice_qfnotice_category_category_category_list',
                        'menu_short_name' => '分类',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-erweimaV6xx',
                        'api_url' => 'qf_notice/category',
                        'router_path' => 'qf_notice/category/category',
                        'view_path' => 'category/category',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '应用分类添加',
                        'menu_key' => 'qf_notice_qfnotice_category_category_category_add',
                        'menu_short_name' => '应用分类添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/category',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应用分类编辑',
                        'menu_key' => 'qf_notice_qfnotice_category_category_category_edit',
                        'menu_short_name' => '应用分类编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应用分类删除',
                        'menu_key' => 'qf_notice_qfnotice_category_category_category_delete',
                        'menu_short_name' => '应用分类删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '群发应用',
                'menu_key' => 'qf_notice_qfnotice_addon_addon_addon',
                'menu_short_name' => '群发应用',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'addon',
                'view_path' => '',
                'methods' => '',
                'sort' => '101',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '应用添加',
                        'menu_key' => 'qf_notice_qfnotice_addon_addon_addon_add',
                        'menu_short_name' => '群发应用添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'qf_notice/addon',
                        'router_path' => 'qf_notice/addon/addon_edit',
                        'view_path' => 'addon/addon_edit',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '群发应用编辑',
                        'menu_key' => 'qf_notice_qfnotice_addon_addon_addon_edit',
                        'menu_short_name' => '群发应用编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/addon/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '群发应用删除',
                        'menu_key' => 'qf_notice_qfnotice_addon_addon_addon_delete',
                        'menu_short_name' => '群发应用删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/addon/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '发送日志',
                'menu_key' => 'qf_notice_qfnotice_log_qflog_qflog',
                'menu_short_name' => '发送日志',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'qflog',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '发送日志添加',
                        'menu_key' => 'qf_notice_qfnotice_log_qflog_qflog_add',
                        'menu_short_name' => '发送日志添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/qflog',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '发送日志编辑',
                        'menu_key' => 'qf_notice_qfnotice_log_qflog_qflog_edit',
                        'menu_short_name' => '发送日志编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/qflog/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '发送日志删除',
                        'menu_key' => 'qf_notice_qfnotice_log_qflog_qflog_delete',
                        'menu_short_name' => '发送日志删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/qflog/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '用户管理',
                'menu_key' => 'qf_notice_qfnotice_user_cat_usercat_userCat',
                'menu_short_name' => '用户分类',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-erweimaV6xx',
                'api_url' => '',
                'router_path' => 'usercat',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '用户分类',
                        'menu_key' => 'qf_notice_qfnotice_user_cat_usercat_userCat_list',
                        'menu_short_name' => '分类',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-liebiaoV6xx',
                        'api_url' => 'qf_notice/usercat',
                        'router_path' => 'qf_notice/usercat/usercat',
                        'view_path' => 'usercat/usercat',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '用户列表',
                        'menu_key' => 'qf_notice_qfnotice_user_user_user_list',
                        'menu_short_name' => '用户',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-dakaixinxiV6xx',
                        'api_url' => 'qf_notice/user',
                        'router_path' => 'qf_notice/user/user',
                        'view_path' => 'user/user',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '用户分类添加',
                        'menu_key' => 'qf_notice_qfnotice_user_cat_usercat_userCat_add',
                        'menu_short_name' => '用户分类添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/usercat',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '用户分类编辑',
                        'menu_key' => 'qf_notice_qfnotice_user_cat_usercat_userCat_edit',
                        'menu_short_name' => '用户分类编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/usercat/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '用户分类删除',
                        'menu_key' => 'qf_notice_qfnotice_user_cat_usercat_userCat_delete',
                        'menu_short_name' => '用户分类删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/usercat/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '模板导入',
                        'menu_key' => 'qf_notice_import',
                        'menu_short_name' => '导入',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-zhankai-yousuojinV6xx',
                        'api_url' => '',
                        'router_path' => 'qf_notice/import',
                        'view_path' => 'import/import',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '用户列',
                'menu_key' => 'qf_notice_qfnotice_user_user_user',
                'menu_short_name' => '用户列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'user',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '用户添加',
                        'menu_key' => 'qf_notice_qfnotice_user_user_user_add',
                        'menu_short_name' => '用户添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/user',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '用户编辑',
                        'menu_key' => 'qf_notice_qfnotice_user_user_user_edit',
                        'menu_short_name' => '用户编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/user/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '用户删除',
                        'menu_key' => 'qf_notice_qfnotice_user_user_user_delete',
                        'menu_short_name' => '用户删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'qf_notice/user/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '发送日志',
                'menu_key' => 'qf_notice_qfnotice_log_qflog_qflog_list',
                'menu_short_name' => '日志',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-wendangV6xx',
                'api_url' => 'qf_notice/qflog',
                'router_path' => 'qflog/qflog',
                'view_path' => 'qflog/qflog',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
];