<?php
return [
    [
        'menu_name' => '会员卡',
        'menu_key' => 'vipcard',
        'menu_short_name' => '会员卡',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconyingyongshichang',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '90',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '概况',
                'menu_key' => 'vipcard_index',
                'menu_short_name' => '概况',
                'menu_type' => '1',
                'icon' => 'iconfont icongaikuang1',
                'api_url' => '',
                'router_path' => 'vipcard/index',
                'view_path' => 'index',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '卡项产品',
                'menu_key' => 'vipcard_goods',
                'menu_short_name' => '卡项',
                'menu_type' => '0',
                'icon' => 'iconfont iconkaxiangchanpin',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '项目管理',
                        'menu_key' => 'vipcard_goods_service',
                        'menu_short_name' => '项目管理',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/service/list',
                        'view_path' => 'service/list',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'vipcard_service_delete',
                                'menu_short_name' => '删除',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '99',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '添加/编辑项目',
                        'menu_key' => 'vipcard_service_add',
                        'menu_short_name' => '添加/编辑项目',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/service/edit',
                        'view_path' => 'service/edit',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '购买记录',
                        'menu_key' => 'vipcard_service_record_list',
                        'menu_short_name' => '购买记录',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/service/record_list',
                        'view_path' => 'service/record_list',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '项目详情',
                        'menu_key' => 'vipcard_service_record_detail',
                        'menu_short_name' => '项目详情',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/service/record_info',
                        'view_path' => 'service/record_info',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '卡项详情',
                        'menu_key' => 'vipcard_card_record_detail',
                        'menu_short_name' => '卡项详情',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/card/record_info',
                        'view_path' => 'card/record_info',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '购买记录',
                        'menu_key' => 'vipcard_card_record_list',
                        'menu_short_name' => '购买记录',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/card/record_list',
                        'view_path' => 'card/record_list',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加/编辑卡项',
                        'menu_key' => 'vipcard_card_add',
                        'menu_short_name' => '添加/编辑卡项',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/card/edit',
                        'view_path' => 'card/edit',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '卡项套餐',
                        'menu_key' => 'vipcard_goods_card',
                        'menu_short_name' => '卡项套餐',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconkaxiangchanpin',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/card/list',
                        'view_path' => 'card/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'vipcard_card_delete',
                                'menu_short_name' => '删除',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '99',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '项目分类',
                        'menu_key' => 'vipcard_goods_category',
                        'menu_short_name' => '项目分类',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmufenlei',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/service/category',
                        'view_path' => 'service/category',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '添加/编辑分类',
                                'menu_key' => 'vipcard_goods_category_edit',
                                'menu_short_name' => '添加/编辑分类',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '99',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除分类',
                                'menu_key' => 'vipcard_goods_category_delete',
                                'menu_short_name' => '删除分类',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '99',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '预约设置',
                        'menu_key' => 'vipcard_reserve_set',
                        'menu_short_name' => '预约设置',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconyuyueshezhi',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/set',
                        'view_path' => 'reserve/set',
                        'methods' => 'get',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '技师管理',
                        'menu_key' => 'vipcard_technician_list',
                        'menu_short_name' => '技师管理',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/technician/list',
                        'view_path' => 'technician/list',
                        'methods' => 'get',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '技师详情',
                        'menu_key' => 'vipcard_technician_info',
                        'menu_short_name' => '技师详情',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'vipcard/goods/technician/info',
                        'view_path' => 'technician/detail',
                        'methods' => 'get',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '卡项订单',
                'menu_key' => 'vipcard_order',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'iconfont iconkaxiangdingdan',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'vipcard_order_list',
                        'menu_short_name' => '订单列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont icona-dingdanliebiao',
                        'api_url' => '',
                        'router_path' => 'vipcard/order/list',
                        'view_path' => 'order',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '项目预约',
                        'menu_key' => 'vipcard_reserve_index',
                        'menu_short_name' => '项目预约',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconyuyuexiangmu',
                        'api_url' => '',
                        'router_path' => 'vipcard/order/reserve',
                        'view_path' => 'reserve/index',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '取消预约',
                                'menu_key' => 'vipcard_reserve_cancel',
                                'menu_short_name' => '取消预约',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '97',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加/编辑预约',
                                'menu_key' => 'vipcard_reserve_edit',
                                'menu_short_name' => '添加/编辑预约',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '97',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '订单详情',
                        'menu_key' => 'vipcard_order_info',
                        'menu_short_name' => '订单详情',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'vipcard/order/detail',
                        'view_path' => 'order_detail',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单核销',
                        'menu_key' => 'vipcard_verify',
                        'menu_short_name' => '订单核销',
                        'menu_type' => '1',
                        'icon' => 'iconfont icondingdanhexiao',
                        'api_url' => '',
                        'router_path' => 'vipcard/order/verify',
                        'view_path' => 'verify',
                        'methods' => 'get',
                        'sort' => '93',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '订单维权',
                        'menu_key' => 'vipcard_refund',
                        'menu_short_name' => '订单维权',
                        'menu_type' => '1',
                        'icon' => 'iconfont icondingdanweiquan',
                        'api_url' => '',
                        'router_path' => 'vipcard/order/refund',
                        'view_path' => 'refund',
                        'methods' => 'get',
                        'sort' => '92',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
        ],
    ],
];