<?php
return [
    [
        'menu_name' => '会员权益',
        'menu_key' => 'tk_vip_tkvip_order_order_order',
        'menu_short_name' => '会员',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-huiyuandengjiV6xx',
        'api_url' => '',
        'router_path' => 'order',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '基本设置',
                'menu_key' => 'tk_vip_config',
                'menu_short_name' => '设置',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
                'api_url' => '',
                'router_path' => 'tk_vip/base/config',
                'view_path' => 'config/index',
                'methods' => 'post',
                'sort' => '110',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '实名管理',
                'menu_key' => 'tk_vip_tkvip_real_real_real',
                'menu_short_name' => '实名',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-yinhangkaV6xx',
                'api_url' => '',
                'router_path' => 'real',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '认证列表',
                        'menu_key' => 'tk_vip_tkvip_real_real_real_list',
                        'menu_short_name' => '列表',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-zhankai-yousuojinV6xx',
                        'api_url' => 'tk_vip/real',
                        'router_path' => 'tk_vip/real/real',
                        'view_path' => 'real/real',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '实名认证添加',
                        'menu_key' => 'tk_vip_tkvip_real_real_real_add',
                        'menu_short_name' => '实名认证添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/real',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '实名认证编辑',
                        'menu_key' => 'tk_vip_tkvip_real_real_real_edit',
                        'menu_short_name' => '实名认证编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/real/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '实名认证删除',
                        'menu_key' => 'tk_vip_tkvip_real_real_real_delete',
                        'menu_short_name' => '实名认证删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/real/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '实名配置',
                        'menu_key' => 'tk_vip_real',
                        'menu_short_name' => '配置',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-wodeV6xx-11',
                        'api_url' => '',
                        'router_path' => 'tk_vip/config/real',
                        'view_path' => 'config/real',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '会员VIP管理',
                'menu_key' => 'tk_vip_tkvip_vip_vip_vip',
                'menu_short_name' => '会员VIP管理',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'vip',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '会员VIP管理添加',
                        'menu_key' => 'tk_vip_tkvip_vip_vip_vip_add',
                        'menu_short_name' => '会员VIP管理添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/vip',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员VIP管理编辑',
                        'menu_key' => 'tk_vip_tkvip_vip_vip_vip_edit',
                        'menu_short_name' => '会员VIP管理编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/vip/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员VIP管理删除',
                        'menu_key' => 'tk_vip_tkvip_vip_vip_vip_delete',
                        'menu_short_name' => '会员VIP管理删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/vip/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '会员日志',
                'menu_key' => 'tk_vip_tkvip_vip_log_log_log',
                'menu_short_name' => '会员日志',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'log',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '会员日志添加',
                        'menu_key' => 'tk_vip_tkvip_vip_log_log_log_add',
                        'menu_short_name' => '会员日志添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/log',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员日志编辑',
                        'menu_key' => 'tk_vip_tkvip_vip_log_log_log_edit',
                        'menu_short_name' => '会员日志编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/log/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员日志删除',
                        'menu_key' => 'tk_vip_tkvip_vip_log_log_log_delete',
                        'menu_short_name' => '会员日志删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'tk_vip/log/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '订单列表',
                'menu_key' => 'tk_vip_tkvip_order_order_order_list',
                'menu_short_name' => '订单',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-jifenV6xx',
                'api_url' => 'tk_vip/order',
                'router_path' => 'tk_vip/order/order',
                'view_path' => 'order/order',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => 'VIP管理',
                'menu_key' => 'tk_vip_tkvip_vip_vip_vip_list',
                'menu_short_name' => 'VIP',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-tuikuanV6xx',
                'api_url' => 'tk_vip/vip',
                'router_path' => 'tk_vip/vip/vip',
                'view_path' => 'vip/vip',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '日志列表',
                'menu_key' => 'tk_vip_tkvip_vip_log_log_log_list',
                'menu_short_name' => '日志',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-dakaixinxiV6xx',
                'api_url' => 'tk_vip/log',
                'router_path' => 'tk_vip/log/log',
                'view_path' => 'log/log',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => 'VIP订单添加',
                'menu_key' => 'tk_vip_tkvip_order_order_order_add',
                'menu_short_name' => 'VIP订单添加',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'tk_vip/order',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => 'VIP订单编辑',
                'menu_key' => 'tk_vip_tkvip_order_order_order_edit',
                'menu_short_name' => 'VIP订单编辑',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'tk_vip/order/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => 'VIP订单删除',
                'menu_key' => 'tk_vip_tkvip_order_order_order_delete',
                'menu_short_name' => 'VIP订单删除',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'tk_vip/order/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => 'VIP管理',
        'menu_key' => 'tk_vip_member_manage',
        'menu_short_name' => 'VIP',
        'parent_key' => 'member',
        'menu_type' => '1',
        'icon' => 'nc-iconfont nc-icon-tuikuanV6xx',
        'api_url' => '',
        'router_path' => 'tk_vip/member/vip',
        'view_path' => 'vip/vip',
        'methods' => '',
        'sort' => '80',
        'status' => '1',
        'is_show' => '1',
    ],
    [
        'menu_name' => '实名管理',
        'menu_key' => 'tk_vip_member_site_real',
        'menu_short_name' => '实名',
        'parent_key' => 'member',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-yinhangkaV6xx',
        'api_url' => '',
        'router_path' => 'tk_vip/member/sitereal',
        'view_path' => '',
        'methods' => '',
        'sort' => '79',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '认证列表',
                'menu_key' => 'tk_vip_site_real_real_real_list',
                'menu_short_name' => '列表',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-zhankai-yousuojinV6xx',
                'api_url' => 'tk_vip/real',
                'router_path' => 'tk_vip/site/real/real',
                'view_path' => 'real/real',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '实名认证添加',
                'menu_key' => 'tk_vip_tkvip_real_real_real_add',
                'menu_short_name' => '实名认证添加',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'tk_vip/real',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '实名认证编辑',
                'menu_key' => 'tk_vip_tkvip_real_real_real_edit',
                'menu_short_name' => '实名认证编辑',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'tk_vip/real/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '实名认证删除',
                'menu_key' => 'tk_vip_tkvip_real_real_real_delete',
                'menu_short_name' => '实名认证删除',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'tk_vip/real/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '实名配置',
                'menu_key' => 'tk_vip_site_memberreal',
                'menu_short_name' => '配置',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-wodeV6xx-11',
                'api_url' => '',
                'router_path' => 'tk_vip/site/config/real',
                'view_path' => 'config/real',
                'methods' => 'post',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
];