<?php
return [
    [
        'menu_name' => '多域名授权',
        'menu_key' => 'hlwoauth',
        'menu_short_name' => '多域名授权',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '授权管理',
                'menu_key' => 'hlwoauth_domain_list',
                'menu_short_name' => '授权管理',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-yingyongliebiaoV6xx',
                'api_url' => 'hlwoauth/domain',
                'router_path' => 'hlwoauth/domain',
                'view_path' => 'hlwoauth/domain',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '授权添加',
                'menu_key' => 'hlwoauth_domain_add',
                'menu_short_name' => '授权添加',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'hlwoauth/domain',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '授权编辑',
                'menu_key' => 'hlwoauth_domain_edit',
                'menu_short_name' => '授权编辑',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'hlwoauth/domain/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '授权删除',
                'menu_key' => 'hlwoauth_domain_delete',
                'menu_short_name' => '授权删除',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'hlwoauth/domain/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];