<?php
return [
    [
        "name" => "礼品卡模板", // 海报模板名称
        'type' => 'shop_giftcard_give', // 海报类型
        "data" => [
            "global" => [
                "width" => 720,
                "height" => 1280,
                "bgType" => "url",
                "bgColor" => "#ffffff",
                "bgUrl" => "addon/shop_giftcard/poster/giftcard_bg.jpg"
            ],
            "value" => [
                [
                    "type" => "image",
                    "path" => "headimg",
                    "uses" => 1,
                    "relate" => "headimg",
                    "value" => "",
                    "id" => "3udia8f040q0",
                    "componentName" => "HeadImg",
                    "componentTitle" => "头像",
                    "width" => 152,
                    "height" => 152,
                    "minWidth" => 60,
                    "minHeight" => 60,
                    "x" => 284,
                    "y" => 190,
                    "angle" => 0,
                    "zIndex" => 1,
                    "shape" => "circle"
                ],
                [
                    "type" => "image",
                    "path" => "giftcard-image",
                    "uses" => 1,
                    "relate" => "giftcard_image",
                    "value" => "",
                    "id" => "1zzzejhs1dxc",
                    "componentName" => "GiftCardImage",
                    "componentTitle" => "礼品卡图片",
                    "width" => 580,
                    "height" => 353,
                    "minWidth" => 60,
                    "minHeight" => 60,
                    "x" => 68,
                    "y" => 442,
                    "angle" => 0,
                    "zIndex" => 2,
                    "shape" => "normal"
                ],
                [
                    "type" => "text",
                    "path" => "giftcard-name",
                    "uses" => 1,
                    "relate" => "giftcard_name",
                    "value" => "",
                    "id" => "5m9q48v0o200",
                    "componentName" => "GiftCardName",
                    "componentTitle" => "礼品卡名称",
                    "width" => 482,
                    "height" => 52,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => 30,
                    "y" => 1102,
                    "angle" => 0,
                    "zIndex" => 3,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 34,
                    "weight" => false,
                    "lineHeight" => 20,
                    "fontColor" => "#FFFFFF"
                ],
                [
                    "type" => "text",
                    "path" => "giftcard-blessing",
                    "uses" => 1,
                    "relate" => "giftcard_blessing",
                    "value" => "",
                    "id" => "eglgnnshofk",
                    "componentName" => "GiftCardBlessing",
                    "componentTitle" => "祝福语",
                    "width" => 482,
                    "height" => 116,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => 119,
                    "y" => 850,
                    "angle" => 0,
                    "zIndex" => 4,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 40,
                    "weight" => false,
                    "lineHeight" => 10,
                    "fontColor" => "#EE1010"
                ],
                [
                    "type" => "qrcode",
                    "path" => "qrcode",
                    "uses" => 1,
                    "relate" => "url",
                    "value" => "",
                    "id" => "257nlym5fvhc",
                    "componentName" => "Qrcode",
                    "componentTitle" => "二维码",
                    "width" => 151,
                    "height" => 151,
                    "minWidth" => 60,
                    "minHeight" => 60,
                    "x" => 539,
                    "y" => 1100,
                    "angle" => 0,
                    "zIndex" => 5
                ],
                [
                    "type" => "text",
                    "path" => "nickname",
                    "uses" => 1,
                    "relate" => "nickname",
                    "value" => "",
                    "id" => "1mypcdr4smzk",
                    "componentName" => "NickName",
                    "componentTitle" => "昵称",
                    "width" => 576,
                    "height" => 49,
                    "minWidth" => 120,
                    "minHeight" => 50,
                    "x" => "center",
                    "y" => 362,
                    "angle" => 0,
                    "zIndex" => 6,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 36,
                    "weight" => false,
                    "lineHeight" => 10,
                    "fontColor" => "#303133"
                ],
                [
                    "type" => "text",
                    "path" => "text",
                    "uses" => 0,
                    "relate" => "",
                    "value" => "长按识别二维码领取你的礼品",
                    "id" => "3z7lbkagxkg0",
                    "componentName" => "Text",
                    "componentTitle" => "文本",
                    "width" => 483,
                    "height" => 42,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => 30,
                    "y" => 1156,
                    "angle" => 0,
                    "zIndex" => 7,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 25,
                    "weight" => false,
                    "lineHeight" => 25,
                    "fontColor" => "#FFFFFF"
                ],
                [
                    "type" => "text",
                    "path" => "giftcard-validity",
                    "uses" => 1,
                    "relate" => "giftcard_validity",
                    "value" => "",
                    "id" => "vrkt0eld3o0",
                    "componentName" => "GiftCardValidity",
                    "componentTitle" => "礼品卡有效期",
                    "width" => 484,
                    "height" => 45,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => 30,
                    "y" => 1200,
                    "angle" => 0,
                    "zIndex" => 9,
                    "fontFamily" => "static/font/SourceHanSansCN-Regular.ttf",
                    "fontSize" => 25,
                    "weight" => false,
                    "lineHeight" => 30,
                    "fontColor" => "#FFFFFF"
                ]
            ]
        ]
    ],
];