<?php
return [
    [
        'menu_name' => '快速支付',
        'menu_key' => 'fast_pay',
        'menu_short_name' => '快速支付',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '基本配置',
                'menu_key' => 'fast_pay_hello_world',
                'menu_short_name' => '配置',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
                'api_url' => 'fast_pay/hello_world',
                'router_path' => 'fast_pay/config/index',
                'view_path' => 'config/index',
                'methods' => 'get',
                'sort' => '999',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '订单列表',
                'menu_key' => 'fast_pay_fastpay_order_order_order_list',
                'menu_short_name' => '列表',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-fenxiaoV6xx1',
                'api_url' => 'fast_pay/order',
                'router_path' => 'fast_pay/order/order',
                'view_path' => 'order/order',
                'methods' => 'get',
                'sort' => '998',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '商户列',
                'menu_key' => 'fast_pay_fastpay_business_business_business',
                'menu_short_name' => '商户列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'business',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '商户列添加',
                        'menu_key' => 'fast_pay_fastpay_business_business_business_add',
                        'menu_short_name' => '商户列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/business',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户列编辑',
                        'menu_key' => 'fast_pay_fastpay_business_business_business_edit',
                        'menu_short_name' => '商户列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/business/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户列删除',
                        'menu_key' => 'fast_pay_fastpay_business_business_business_delete',
                        'menu_short_name' => '商户列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/business/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '商户订单列',
                'menu_key' => 'fast_pay_fastpay_business_order_businessorder_businessOrder',
                'menu_short_name' => '商户订单列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'businessorder',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '商户订单列添加',
                        'menu_key' => 'fast_pay_fastpay_business_order_businessorder_businessOrder_add',
                        'menu_short_name' => '商户订单列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessorder',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户订单列编辑',
                        'menu_key' => 'fast_pay_fastpay_business_order_businessorder_businessOrder_edit',
                        'menu_short_name' => '商户订单列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessorder/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户订单列删除',
                        'menu_key' => 'fast_pay_fastpay_business_order_businessorder_businessOrder_delete',
                        'menu_short_name' => '商户订单列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessorder/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '商户活动',
                'menu_key' => 'fast_pay_fastpay_business_active_businessactive_businessActive',
                'menu_short_name' => '商户活动',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'businessactive',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '商户活动列表',
                        'menu_key' => 'fast_pay_fastpay_business_active_businessactive_businessActive_list',
                        'menu_short_name' => '商户活动列表',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessactive',
                        'router_path' => 'businessactive/businessactive',
                        'view_path' => 'businessactive/businessactive',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商户活动添加',
                        'menu_key' => 'fast_pay_fastpay_business_active_businessactive_businessActive_add',
                        'menu_short_name' => '商户活动添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessactive',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户活动编辑',
                        'menu_key' => 'fast_pay_fastpay_business_active_businessactive_businessActive_edit',
                        'menu_short_name' => '商户活动编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessactive/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户活动删除',
                        'menu_key' => 'fast_pay_fastpay_business_active_businessactive_businessActive_delete',
                        'menu_short_name' => '商户活动删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessactive/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '商户会员',
                'menu_key' => 'fast_pay_fastpay_business_member_businessmember_businessMember',
                'menu_short_name' => '商户会员',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'businessmember',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '商户会员添加',
                        'menu_key' => 'fast_pay_fastpay_business_member_businessmember_businessMember_add',
                        'menu_short_name' => '商户会员添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessmember',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户会员编辑',
                        'menu_key' => 'fast_pay_fastpay_business_member_businessmember_businessMember_edit',
                        'menu_short_name' => '商户会员编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessmember/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商户会员删除',
                        'menu_key' => 'fast_pay_fastpay_business_member_businessmember_businessMember_delete',
                        'menu_short_name' => '商户会员删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/businessmember/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '支付订单',
                'menu_key' => 'fast_pay_fastpay_order_order_order',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-youhuiV6xx1',
                'api_url' => '',
                'router_path' => 'order',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '快速支付订单添加',
                        'menu_key' => 'fast_pay_fastpay_order_order_order_add',
                        'menu_short_name' => '快速支付订单添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/order',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '快速支付订单编辑',
                        'menu_key' => 'fast_pay_fastpay_order_order_order_edit',
                        'menu_short_name' => '快速支付订单编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '快速支付订单删除',
                        'menu_key' => 'fast_pay_fastpay_order_order_order_delete',
                        'menu_short_name' => '快速支付订单删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '商户管理',
                'menu_key' => 'fast_pay_fastpay_business_business_business_list',
                'menu_short_name' => '商户管理',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-erweimaV6xx-1',
                'api_url' => 'fast_pay/business',
                'router_path' => 'business/business',
                'view_path' => 'business/business',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '商户订单',
                'menu_key' => 'fast_pay_fastpay_business_order_businessorder_businessOrder_list',
                'menu_short_name' => '商户订单',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-tuikuanV6xx1',
                'api_url' => 'fast_pay/businessorder',
                'router_path' => 'businessorder/businessorder',
                'view_path' => 'businessorder/businessorder',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '商户会员',
                'menu_key' => 'fast_pay_fastpay_business_member_businessmember_businessMember_list',
                'menu_short_name' => '商户会员',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-huiyuandengjiV6xx1',
                'api_url' => 'fast_pay/businessmember',
                'router_path' => 'businessmember/businessmember',
                'view_path' => 'businessmember/businessmember',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '服务商',
                'menu_key' => 'fast_pay_business_config',
                'menu_short_name' => '服务商',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-yinhangkaV6xx',
                'api_url' => '',
                'router_path' => 'fast_pay/business/config',
                'view_path' => 'config/business',
                'methods' => 'post',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];