<?php
return [
    [
        'menu_name' => '快速支付',
        'menu_key' => 'fast_pay',
        'menu_short_name' => '快速支付',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '基本配置',
                'menu_key' => 'fast_pay_hello_world',
                'menu_short_name' => '配置',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
                'api_url' => 'fast_pay/hello_world',
                'router_path' => 'fast_pay/config/index',
                'view_path' => 'config/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '支付订单',
                'menu_key' => 'fast_pay_fastpay_order_order_order',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-youhuiV6xx1',
                'api_url' => '',
                'router_path' => 'order',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '快速支付订单添加',
                        'menu_key' => 'fast_pay_fastpay_order_order_order_add',
                        'menu_short_name' => '快速支付订单添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/order',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '快速支付订单编辑',
                        'menu_key' => 'fast_pay_fastpay_order_order_order_edit',
                        'menu_short_name' => '快速支付订单编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '快速支付订单删除',
                        'menu_key' => 'fast_pay_fastpay_order_order_order_delete',
                        'menu_short_name' => '快速支付订单删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fast_pay/order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '订单列表',
                'menu_key' => 'fast_pay_fastpay_order_order_order_list',
                'menu_short_name' => '列表',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-fenxiaoV6xx1',
                'api_url' => 'fast_pay/order',
                'router_path' => 'fast_pay/order/order',
                'view_path' => 'order/order',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
];