<?php
return [
    [
        'menu_name' => '手机保修查询',
        'menu_key' => 'hsx_phone_query',
        'menu_short_name' => '手机保修查询',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont icongaikuang1',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            // [
            //     'menu_name' => '手机保修查询',
            //     'menu_key' => 'hsx_phone_query',
            //     'menu_short_name' => '手机保修查询',
            //     'menu_type' => '1',
            //     'icon' => 'iconfont icongaikuang1',
            //     'api_url' => 'hsx_phone_query/hello_world',
            //     'router_path' => 'hsx_phone_query/hello_world',
            //     'view_path' => 'hello_world/index',
            //     'methods' => 'get',
            //     'sort' => '100',
            //     'status' => '1',
            //     'is_show' => '1',
            // ],
            // [
            //     'menu_name' => '配置',
            //     'menu_key' => 'hsx_phone_query_config',
            //     'menu_short_name' => '手机保修查询',
            //     'menu_type' => '1',
            //     'icon' => 'iconfont icongaikuang1',
            //     'api_url' => 'hsx_phone_query/hello_world',
            //     'router_path' => 'hsx_phone_query_config/hsx_phone_query_config',
            //     'view_path' => 'hsx_phone_query_config/hsx_phone_query_config',
            //     'methods' => 'get',
            //     'sort' => '100',
            //     'status' => '1',
            //     'is_show' => '1',
            // ],
            // [
            //     'menu_name' => '分类列表',
            //     'menu_key' => 'hsx_phone_query_category',
            //     'menu_short_name' => '手机保修查询',
            //     'menu_type' => '1',
            //     'icon' => 'iconfont icongaikuang1',
            //     'api_url' => 'hsx_phone_query/hello_world',
            //     'router_path' => 'hsx_phone_query_category/hsx_phone_query_category',
            //     'view_path' => 'hsx_phone_query_category/hsx_phone_query_category',
            //     'methods' => 'get',
            //     'sort' => '100',
            //     'status' => '1',
            //     'is_show' => '1',
            // ],
        ],
    ],
];