<?php
return [
    [
        'menu_name' => 'TK工具',
        'menu_key' => 'tk_devtool',
        'menu_short_name' => '工具',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element-Tickets',
        'api_url' => '',
        'router_path' => 'tk_devtool',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '打包工具',
                'menu_key' => 'tk_devtool_admin_index',
                'menu_short_name' => '打包工具',
                'menu_type' => '1',
                'icon' => 'iconfont-icona-shouyediannao',
                'api_url' => '',
                'router_path' => 'tk_devtool_index',
                'view_path' => 'tk_devtool/index',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '数据库管理',
                'menu_key' => 'tk_devtool_admin_database',
                'menu_short_name' => '数据库',
                'menu_type' => '1',
                'icon' => 'iconfont-iconlianmengguanli',
                'api_url' => '',
                'router_path' => 'tk_devtool_admin_database',
                'view_path' => 'tk_devtool/database',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '更新助手',
                'menu_key' => 'tk_devtool_admin_gittool',
                'menu_short_name' => '更新助手',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'tk_devtool_gittool',
                'view_path' => 'tk_devtool/gittool',
                'methods' => '',
                'sort' => '1',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '数据库编辑',
                'menu_key' => 'tk_devtool_admin_database_edit',
                'menu_short_name' => '数据库编辑',
                'menu_type' => '1',
                'icon' => 'iconfont-iconwangzhan1',
                'api_url' => '',
                'router_path' => 'tk_devtool_admin_database_edit',
                'view_path' => 'tk_devtool/database-edit',
                'methods' => '',
                'sort' => '1',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];