<?php
return [
    [
        'menu_name' => '礼品卡',
        'menu_key' => 'shop_giftcard',
        'menu_short_name' => '礼品卡',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconyingyongshichang',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '110',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '礼品卡列表',
                'menu_key' => 'shop_giftcard_list',
                'menu_short_name' => '礼品卡列表',
                'menu_type' => '1',
                'icon' => 'iconfont iconshangpinliebiao1',
                'api_url' => 'shop_giftcard/giftcard',
                'router_path' => 'shop_giftcard/giftcard/list',
                'view_path' => 'giftcard/list',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '礼品卡排序号修改',
                        'menu_key' => 'shop_giftcard_sort_edit',
                        'menu_short_name' => '礼品卡排序号修改',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/giftcard/sort',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '礼品卡状态修改',
                        'menu_key' => 'shop_giftcard_status_edit',
                        'menu_short_name' => '礼品卡状态修改',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/giftcard/status',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '礼品卡删除',
                        'menu_key' => 'shop_giftcard_delete',
                        'menu_short_name' => '礼品卡删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/giftcard/delete',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '礼品卡分类',
                'menu_key' => 'shop_giftcard_category_list',
                'menu_short_name' => '礼品卡分类',
                'menu_type' => '1',
                'icon' => 'iconfont iconshangpinfenlei',
                'api_url' => 'shop_giftcard/category',
                'router_path' => 'shop_giftcard/category',
                'view_path' => 'giftcard/category',
                'methods' => 'get',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '礼品卡分类添加',
                        'menu_key' => 'shop_giftcard_category_add',
                        'menu_short_name' => '礼品卡分类',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/category',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '礼品卡分类编辑',
                        'menu_key' => 'shop_goods_category_edit',
                        'menu_short_name' => '礼品卡分类编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '礼品卡分类删除',
                        'menu_key' => 'shop_goods_category_delete',
                        'menu_short_name' => '礼品卡分类删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/category/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '礼品卡分类排序号修改',
                        'menu_key' => 'shop_giftcard_category_sort_edit',
                        'menu_short_name' => '礼品卡分类排序号修改',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/category/sort',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '礼品卡分类状态修改',
                        'menu_key' => 'shop_giftcard_category_status',
                        'menu_short_name' => '礼品卡分类状态修改',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/category/status',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '礼品卡设置',
                'menu_key' => 'shop_giftcard_config',
                'menu_short_name' => '礼品卡设置',
                'menu_type' => '1',
                'icon' => 'iconfont iconshangpinfenlei',
                'api_url' => 'shop_giftcard/config',
                'router_path' => 'shop_giftcard/config',
                'view_path' => 'giftcard/config',
                'methods' => 'get',
                'sort' => '98',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '素材管理',
                'menu_key' => 'shop_giftcard_material_list',
                'menu_short_name' => '素材管理',
                'menu_type' => '1',
                'icon' => 'iconfont iconshangpinfenlei',
                'api_url' => 'shop_giftcard/material',
                'router_path' => 'shop_giftcard/material',
                'view_path' => 'giftcard/material',
                'methods' => 'get',
                'sort' => '97',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '素材添加',
                        'menu_key' => 'shop_giftcard_material_add',
                        'menu_short_name' => '素材添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/material',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '素材编辑',
                        'menu_key' => 'shop_goods_material_edit',
                        'menu_short_name' => '素材编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/material/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '素材删除',
                        'menu_key' => 'shop_goods_material_delete',
                        'menu_short_name' => '素材删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/material/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '素材分组列表',
                'menu_key' => 'shop_giftcard_material_group_list',
                'menu_short_name' => '素材分组列表',
                'menu_type' => '1',
                'icon' => 'iconfont iconshangpinfenlei',
                'api_url' => 'shop_giftcard/material/group',
                'router_path' => 'shop_giftcard/material/group',
                'view_path' => 'giftcard/material_group',
                'methods' => 'get',
                'sort' => '96',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '素材分组编辑',
                        'menu_key' => 'shop_goods_material_group_edit',
                        'menu_short_name' => '素材分组编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/material/group/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '素材分组添加',
                        'menu_key' => 'shop_giftcard_material_group_add',
                        'menu_short_name' => '素材分组添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/material/group',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '素材分组删除',
                        'menu_key' => 'shop_goods_material_group_delete',
                        'menu_short_name' => '素材分组删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'shop_giftcard/material/group/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '删除制卡',
                'menu_key' => 'shop_giftcard_makecard_delete',
                'menu_short_name' => '删除制卡',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'shop_giftcard/makecard/delete',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '制卡',
                'menu_key' => 'shop_giftcard_makecard',
                'menu_short_name' => '制卡',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'shop_giftcard/makecard',
                'view_path' => 'giftcard/makecard',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '卡详情',
                'menu_key' => 'shop_giftcard_card_detail',
                'menu_short_name' => '卡详情',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'shop_giftcard/giftcard/card_detail',
                'view_path' => 'giftcard/card_detail',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '礼品卡详情',
                'menu_key' => 'shop_giftcard_detail',
                'menu_short_name' => '礼品卡详情',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'shop_giftcard/giftcard/detail',
                'view_path' => 'giftcard/detail',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '礼品卡编辑',
                'menu_key' => 'shop_giftcard_edit',
                'menu_short_name' => '礼品卡编辑',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'shop_giftcard/giftcard/<id>',
                'router_path' => 'shop_giftcard/giftcard/edit',
                'view_path' => 'giftcard/edit',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '礼品卡添加',
                'menu_key' => 'shop_giftcard_add',
                'menu_short_name' => '礼品卡添加',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'shop_giftcard/giftcard',
                'router_path' => 'shop_giftcard/giftcard/edit',
                'view_path' => 'giftcard/edit',
                'methods' => 'post',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => '礼品卡订单',
        'menu_key' => 'shop_giftcard_order_list',
        'menu_short_name' => '礼品卡订单',
        'parent_key' => 'shop_order',
        'menu_type' => '1',
        'icon' => 'iconfont icona-dingdanliebiao',
        'api_url' => 'shop_giftcard/order',
        'router_path' => 'shop_giftcard/order/list',
        'view_path' => 'order/list',
        'methods' => '',
        'sort' => '99',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '商家留言',
                'menu_key' => 'shop_giftcard_order_remark',
                'menu_short_name' => '商家留言',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'shop_giftcard/order/shop_remark',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '订单关闭',
                'menu_key' => 'shop_giftcard_order_close',
                'menu_short_name' => '订单关闭',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'shop_giftcard/order/close/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => '礼品卡订单详情',
        'menu_key' => 'shop_giftcard_order_detail',
        'menu_short_name' => '礼品卡订单详情',
        'parent_key' => 'shop_order',
        'menu_type' => '1',
        'icon' => 'iconfont iconshangpinguanli',
        'api_url' => 'shop_giftcard/order/<id>',
        'router_path' => 'shop_giftcard/order/detail',
        'view_path' => 'order/detail',
        'methods' => 'get',
        'sort' => '0',
        'status' => '1',
        'is_show' => '0',
    ]
];