<?php
return [
    [
        'menu_name' => '组织结构',
        'menu_key' => 'data_scope',
        'menu_short_name' => '组织',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '部门列表',
                'menu_key' => 'data_scope_hello_world',
                'menu_short_name' => '部门',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'data_scope/sysdept',
                'router_path' => 'data_scope/sysdept',
                'view_path' => 'data_scope/sysdept',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '部门添加',
                        'menu_key' => 'data_scope_data_scope_sys_dept_data_scope_SysDept_add',
                        'menu_short_name' => '部门添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'data_scope/sysdept',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '部门编辑',
                        'menu_key' => 'data_scope_data_scope_sys_dept_data_scope_SysDept_edit',
                        'menu_short_name' => '部门编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'data_scope/sysdept/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '部门删除',
                        'menu_key' => 'data_scope_data_scope_sys_dept_data_scope_SysDept_delete',
                        'menu_short_name' => '部门删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'data_scope/sysdept/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '数据权限',
                'menu_key' => 'data_scope_data_scope_sys_dept_data_scope_SysDept',
                'menu_short_name' => '权限',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'data_scope/role',
                'router_path' => 'data_scope/role',
                'view_path' => 'data_scope/role',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
];