<?php
return [
    [
        'menu_name' => '易东云文档Vite',
        'menu_key' => 'ydc_docvite',
        'menu_short_name' => '易东云文档Vite',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-wendangV6xx',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '配置',
                'menu_key' => 'ydc_docvite_index',
                'menu_short_name' => '配置',
                'menu_type' => '1',
                'icon' => 'iconfont icongaikuang1',
                'api_url' => 'config/index',
                'router_path' => 'ydc_docvite/index',
                'view_path' => 'dashboard/index',
                'methods' => '',
                'sort' => '110',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '编辑配置',
                        'menu_key' => 'ydc_docvite_index_edit',
                        'menu_short_name' => '编辑配置',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'config/edit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '仓库',
                'menu_key' => 'ydc_docvite_vault_index',
                'menu_short_name' => '仓库',
                'menu_type' => '1',
                'icon' => 'iconfont icondingdan',
                'api_url' => '',
                'router_path' => 'ydc_docvite/vault',
                'view_path' => 'vault/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '选择仓库',
                        'menu_key' => 'ydc_docvite_vault_select',
                        'menu_short_name' => '选择仓库',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'vault/select',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '选择仓库和目录',
                        'menu_key' => 'ydc_docvite_vault_select_tree',
                        'menu_short_name' => '选择仓库和目录',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'vault/selectTree',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加仓库',
                        'menu_key' => 'ydc_docvite_vault_add',
                        'menu_short_name' => '添加仓库',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'vault/add',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑仓库',
                        'menu_key' => 'ydc_docvite_vault_edit',
                        'menu_short_name' => '编辑仓库',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'vault/edit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '96',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除仓库',
                        'menu_key' => 'ydc_docvite_vault_del',
                        'menu_short_name' => '删除仓库',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'vault/del',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '发布仓库',
                        'menu_key' => 'ydc_docvite_vault_publish',
                        'menu_short_name' => '发布仓库',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'vault/publish',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '目录',
                'menu_key' => 'ydc_docvite_path_index',
                'menu_short_name' => '目录',
                'menu_type' => '1',
                'icon' => 'iconfont icondingdan',
                'api_url' => '',
                'router_path' => 'ydc_docvite/path',
                'view_path' => 'path/index',
                'methods' => 'get',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '添加目录',
                        'menu_key' => 'ydc_docvite_path_add',
                        'menu_short_name' => '添加目录',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'path/add',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '目录树选择',
                        'menu_key' => 'ydc_docvite_path_selectTree',
                        'menu_short_name' => '目录选择',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'path/selectTree',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑目录',
                        'menu_key' => 'ydc_docvite_path_edit',
                        'menu_short_name' => '编辑目录',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'path/edit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '96',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除目录',
                        'menu_key' => 'ydc_docvite_path_del',
                        'menu_short_name' => '删除目录',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'path/del',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '添加文档',
                'menu_key' => 'ydc_docvite_markdown_add',
                'menu_short_name' => '添加文档',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'ydc_docvite/markdown/add',
                'view_path' => 'markdown/add',
                'methods' => '',
                'sort' => '99',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '文档添加',
                        'menu_key' => 'ydc_docvite_markdown_add_bnt',
                        'menu_short_name' => '文档添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'markdown/add',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '编辑文档',
                'menu_key' => 'ydc_docvite_markdown_edit',
                'menu_short_name' => '编辑文档',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'ydc_docvite/markdown/edit',
                'view_path' => 'markdown/edit',
                'methods' => '',
                'sort' => '99',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '文档编辑',
                        'menu_key' => 'ydc_docvite_markdown_edit_btn',
                        'menu_short_name' => '文档编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'markdown/edit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '文档',
                'menu_key' => 'ydc_docvite_markdown_index',
                'menu_short_name' => '文档',
                'menu_type' => '1',
                'icon' => 'iconfont icondingdan',
                'api_url' => '',
                'router_path' => 'ydc_docvite/markdown',
                'view_path' => 'markdown/index',
                'methods' => 'get',
                'sort' => '98',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '文档详情',
                        'menu_key' => 'ydc_docvite_markdown_detail',
                        'menu_short_name' => '文档详情',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'markdown/detail',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除文档',
                        'menu_key' => 'ydc_docvite_markdown_del',
                        'menu_short_name' => '删除文档',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'markdown/del',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '发布文档',
                        'menu_key' => 'ydc_docvite_markdown_publish',
                        'menu_short_name' => '删除文档',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'markdown/publish',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '96',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];