<?php
return [
    [
        'menu_name' => '存储管理',
        'menu_key' => 'manage_oss_admin',
        'menu_short_name' => '存储',
        'parent_key' => 'setting_manage',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '存储设置',
                'menu_key' => 'manageOss_set_admin',
                'menu_short_name' => '设置',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'manage_oss/manageoss',
                'router_path' => 'manageoss/setadmin',
                'view_path' => 'set/admin_storage',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '存储管理',
                'menu_key' => 'manageOss_list_admin',
                'menu_short_name' => '存储管理列表',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'manage_oss/manageoss',
                'router_path' => 'manageoss/manageoss',
                'view_path' => 'manageoss/manageoss',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '存储管理添加',
                'menu_key' => 'manage_oss_manage_oss_manageoss_manageOss_add',
                'menu_short_name' => '存储管理添加',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'manage_oss/manageoss',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '存储管理编辑',
                'menu_key' => 'manage_oss_manage_oss_manageoss_manageOss_edit',
                'menu_short_name' => '存储管理编辑',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'manage_oss/manageoss/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '存储管理删除',
                'menu_key' => 'manage_oss_manage_oss_manageoss_manageOss_delete',
                'menu_short_name' => '存储管理删除',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'manage_oss/manageoss/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    'delete' => ['setting_storage']
];