<?php
return [
    [
        'menu_name' => '存储设置',
        'menu_key' => 'manageoss_setting_storage',
        'menu_short_name' => '存储设置',
        'parent_key' => 'setting_tool',
        'menu_type' => '1',
        'icon' => 'element FolderChecked',
        'api_url' => '',
        'router_path' => 'manageoss_setting/storage',
        'view_path' => 'set/site_storage',
        'methods' => 'get',
        'sort' => '98',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '获取存储配置',
                'menu_key' => 'setting_storage_value',
                'menu_short_name' => '获取存储配置',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'sys/storage/<storage_type>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '存储设置修改',
                'menu_key' => 'edit_setting_storage',
                'menu_short_name' => '存储设置修改',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'sys/storage/<storage_type>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '存储设置修改',
                'menu_key' => 'edit_setting_storage',
                'menu_short_name' => '存储设置修改',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'sys/storage/<storage_type>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    'delete' => ['setting_storage']
];